### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by 18AS** [Arkadiy-Garber/FeGenie#23] opened 2021-03-17 19:17 UTC
Please help. Running the command (bash setup_noconda.sh) returns an error as given below:

test_dataset/
test_dataset/Aggregatibacter_actinomycetemcomitans.txt
test_dataset/Mariprofundus_ferrooxydans_PV-1.txt
test_dataset/Streptococcus_mutans.txt
test_dataset/Pseudomonas_aeruginosa_PA01.txt
test_dataset/Porphyromonas_gingivalis.txt
test_dataset/Rhodopseudomonas_palustris_TIE-1.txt
test_dataset/Geobacter_bemidjiensis.txt
test_dataset/Shewanella_oneidensis_MR-1.txt
test_dataset/Magnetospirillum_magneticum_AMB-1.txt
test_dataset/Rhodopseudomonas_palustris_TIE-1.txt-proteins.faa
test_dataset/Acidithiobacillus_ferrooxidans.txt
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning in install.packages("grid", repos = "http://cran.us.r-project.org") :
  'lib = "/usr/lib64/R/library"' is not writable
Error in install.packages("grid", repos = "http://cran.us.r-project.org") :
  unable to install packages
Execution halted
Error: unexpected end of input
Execution halted
setup_noconda.sh: line 8: syntax error near unexpected token `('
setup_noconda.sh: line 8: `Rscript -e 'install.packages("ggplot2", repos = "http://cran.us.r-project.org")''

How can I overcome this issue?

**Comment by Arkadiy-Garber** [comment] 2021-03-17 20:38
Hi, thanks for your interest in FeGenie!

It looks like those error messages are caused by a "not writable" directory to which Rscript is attempting to install packages. For me to better help you deal with this issue, can you please tell me 1) whether you are attempting to use FeGenie on a remote server, 2) whether you have super-user (sudo) permissions on this server, and 3) whether you have the opportunity to try running FeGenie on a local machine?

Thanks!
Arkadiy

**Comment by 18AS** [comment] 2021-03-18 03:07
Thanks for your prompt response.
1. Yes, I am using a remote server.
2. I do not have sudo permissions.
3. Not sure. Can try something if you elaborate it. I am not well informed but keen on learning.

BTW, I also tried the conda based installation procedure. I was getting an error related to install.packages. I checked that r wasn't installed. Installed r. 
I tried to run: FeGenie.py -h
Atleast it returned the expected output. How do I confirm if the installation has taken place properly if I tried the right thing?

**Comment by Arkadiy-Garber** [comment] 2021-03-20 02:10
Ok, can you try re-running the setup.sh script (Conda installation) now that R is installed. Also, I think you can try running FeGenie now. Hopefully, the R installation solved the issue. Regardless, the R packages are only responsible for making plots from the main output files, which are written in .csv format. So even with the errors that you are getting, the main FeGenie pipeline should run without a problem. Does that make sense? Let me know if you have any other questions or issues.

**Comment by Arkadiy-Garber** [comment] 2021-03-25 20:28
Hi there,

Just wanted to let you know that I found a few small syntax typos in my setup.sh and setup_noconda.sh scripts. It looks like this may have been causing some installation issues, with respect to the R packages. With the current update, these errors should be fixed.

Thanks,
Arkadiy

**Closed by Arkadiy-Garber** 2021-03-25 20:28 UTC
